services:
  postgres:
    container_name: desafio_modulo_4
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5437:5432
